### ISSUE TITLE
Add table generators builder

### ISSUE THREAD

**Issue by kombatkos** [surfstudio/ReactiveDataDisplayManager#188]
the idea is this: to make a builder for table generators.
You can add a collection of basic type generators (Spacer, Text, Button) as in swiftUI, using a separate library.
This will speed up writing tables and remove a lot of unnecessary code from projects.

**Builder:**

<img width="764" alt="Снимок экрана 2022-07-04 в 12 17 55" src="https://user-images.githubusercontent.com/56546669/177113379-3b62de05-b433-4432-a5f5-97eaf7006ef1.png">

**Use:**

<img width="381" alt="Снимок экрана 2022-07-04 в 12 18 34" src="https://user-images.githubusercontent.com/56546669/177113507-99733fea-07fd-4f79-9cce-01d622fc777d.png">

**Comment by NullIsOne** [comment]
Good suggestion.
We could add this to roadmap.
We could create subspec with this, but some people are using our lib through SPM so, we need to think little bit more.
Maybe separate repo with utils will be better solution..

**Comment by NullIsOne** [comment]
Resolved in #195
