### ISSUE TITLE
Generators reuse

### ISSUE THREAD

**Issue by ismetanin** [surfstudio/ReactiveDataDisplayManager#29]
Now we have a problem with the number of generators if we need to create a table with a large number of cells

**Comment by NullIsOne** [comment]
You can try `BaseCellGenerator` for most common cases, when you need to configure cell with some model.
Just conform cell to `Configurable` and init generator.
You can find more information in our Readme.

Issue seems to be outdated. So, closing it.

**Comment by ismetanin** [comment]
@NullIsOne 
The issue was about the linear corellation between number of generators and number of cells.
Even if you use `BaseCellGenerator` you create N generators for N cells, right?

**Comment by NullIsOne** [comment]
Got it.
Yes, we have 1 to 1 relation between generator and cell.
Btw, generator is lightweight entity and can't produce any serious memory issues or something like this.
Thats why we don't need to decrease generators count.
