### ISSUE TITLE
Add proxying

### ISSUE THREAD

**Issue by LastSprint** [surfstudio/ReactiveDataDisplayManager#34]
Needs to proxying DataSource/TableView/ScrollView methods to events

**Comment by NullIsOne** [comment]
Starting from **7.0.0** we have added plugins.
With this plugins you can easily proxy any table/collection/scrollview event. 

Also we have bult-in plugins like `TableScrollViewDelegateProxyPlugin`
Please, try the last version after release. This will be very soon.

For now, I'm closing issue
