### ISSUE TITLE
Add update transaction

### ISSUE THREAD

**Issue by LastSprint** [surfstudio/ReactiveDataDisplayManager#36]
Add possibility to make any actions with adapter inside `beginUpdate()` - `endUpdate()`

**Comment by NullIsOne** [comment]
We introduced `Animator` for this purpose

```
animator?.perform(in: view, animated: true) { [weak view] in
    view?.reloadRows(at: indexPaths, with: .automatic)
}
```

We have implemented two animators for `UITableView`

1. `TableUpdatesAnimator` based on  `beginUpdate() - endUpdate()`
2. `TableBatchUpdatesAnimator` based on `performBatchUpdates`

Please, keep in mind that `beginUpdate() - endUpdate()` is deprecated.
So, better to use `TableBatchUpdatesAnimator` from iOS 11
