### ISSUE TITLE
PaginableBaseTDDM don't work properly

### ISSUE THREAD

**Issue by alexfilimon** [surfstudio/ReactiveDataDisplayManager#46]
`PaginableBaseTableDataDisplayManager` calls `lastCellShowingEvent` for every section. 
Maybe will be better to make calling `lastCellShowingEvent` only for last section?

**Comment by ismetanin** [comment]
Or maybe we should delete this DDM? @LastSprint

**Comment by LastSprint** [comment]
Seems like a bug. I will think about it. On this time I think needs to make this class internal

**Comment by ismetanin** [comment]
@LastSprint Why internal?
