### ISSUE TITLE
Add swipe actions to generator

### ISSUE THREAD

**Issue by alexfilimon** [surfstudio/ReactiveDataDisplayManager#56]
I have code, that works only iOS 11+, because it uses `UIContextualAction`. Maybe we should support this feature only for iOS 11+?

**Comment by NullIsOne** [comment]
We introduced plugin concepts in **7.0.0** 
With `TableSwipeActionsConfigurationPlugin` you can easily add swipe actions for your table.

1. Specify available actions UI in `TableSwipeActionsProvider` 
2. Specify enabled for concrete cell actions with conforming generator to `SwipeableItem`
3. Add `TableSwipeActionsConfigurationPlugin` to manager.

You can look at example in our example project.
I will notify you when we release **7.0.0**. But even now, you already can check this feature in develop branch or in PR #93
