### ISSUE TITLE
Can't build example project

### ISSUE THREAD

**Issue by NullIsOne** [surfstudio/ReactiveDataDisplayManager#72]
Checked on Xcode 11.6

- Fetch repository
- Install pods
- Try build example project

**Actual result:** failed with `Content and frame layout guides before iOS 11.0`
**Expected result:** build running on simulator or device

--
**Possible workarounds**

1. Uncheck `Content layout Guides` in Main.storyboard/StackScene/Stack/View/ScrollView
2. Disable supporting of iOS 10 and up minimum target to iOS 11

**Comment by Puasonych** [comment]
Looks like already resolved. iOS deployment target is 11.2. I checked on two simulators iOS 11.4/14.1 and device iOS 14.4.

**Comment by NullIsOne** [comment]
You're right. Thanks fro contributing
